### ISSUE TITLE
import package exception

### ISSUE THREAD

**Issue by AdamLan** [baiyapeng/crawler#1]
Consumer.java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
not found.

**Comment by baiyapeng** [comment]
@AdamLan 你看下 `jsoup`的包是否已经引入
`<dependency>
			
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.10.3</version>
		</dependency>`

**Comment by baiyapeng** [comment]
最好在这里下载源码到本地进行构建，选择 `ZIP`类型，解压并导入就可以了

**Comment by baiyapeng** [comment]
另外，你的头像好犀利
